services:
  rabbitmq:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - net-dev

volumes:
  rabbitmq-data:

networks:
  net-dev:
    driver: bridge
