services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - volume-postgres:/var/lib/postgres/data
    networks:
      - net-dev
    command: >
      bash -c "apt-get update &&
               apt-get install -y postgis postgresql-17-postgis-3 &&
               docker-entrypoint.sh postgres"

volumes:
  volume-postgres:

networks:
  net-dev:
    driver: bridge