services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net-dev

volumes:
  redis-data:

networks:
  net-dev:
    driver: bridge